In [90]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [91]:
import sys
print(sys.executable)

c:\Users\cbe\AppData\Local\Programs\Python\Python311\python.exe

In [108]:
import sys
import os

# Adds the root directory ('portfolio_optimization') to the python path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), os.pardir)))

from src.data_loader import *
from src.data_understand import *
from src.data_explore import *

### 1: Data Exploration and Enrichment

#### # Load Dataset

In [65]:
excel_path = ("C:/Users/CBE/Desktop/week 11/ethiopia_fi_forecast/data/raw/ethiopia_fi_unified_data.xlsx")

reference_path = ("C:/Users/CBE/Desktop/week 11/ethiopia_fi_forecast/data/raw/reference_codes.xlsx")

In [66]:
# Load the data sheet
df = load_dataset(excel_path,sheet_name="ethiopia_fi_unified_data")
df.head()

✓ Dataset loaded successfully.

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN

In [67]:
impact_df = load_dataset(excel_path,sheet_name="Impact_sheet")
impact_df.head()

✓ Dataset loaded successfully.

,record_id,parent_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,IMP_0001,EVT_0001,impact_link,NaN,ACCESS,Telebirr effect on Account Ownership,NaN,NaN,15.0,NaN,...,increase,high,15.0,12,literature,Kenya,Example_Trainee,2025-01-20,NaN,Kenya M-Pesa showed +20pp over 5 years
1,IMP_0002,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on Telebirr Users,NaN,NaN,NaN,NaN,...,increase,high,NaN,3,empirical,NaN,Example_Trainee,2025-01-20,NaN,Direct subscriber acquisition
2,IMP_0003,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on P2P Transactions,NaN,NaN,25.0,NaN,...,increase,high,25.0,6,empirical,NaN,Example_Trainee,2025-01-20,NaN,New digital payment channel
3,IMP_0004,EVT_0002,impact_link,NaN,ACCESS,Safaricom effect on 4G Coverage,NaN,NaN,15.0,NaN,...,increase,medium,15.0,12,empirical,NaN,Example_Trainee,2025-01-20,NaN,Network investment from competition
4,IMP_0005,EVT_0002,impact_link,NaN,AFFORDABILITY,Safaricom effect on Data Affordability,NaN,NaN,-20.0,NaN,...,decrease,medium,-20.0,12,literature,Rwanda,Example_Trainee,2025-01-20,NaN,Competition typically reduces prices

In [70]:
reference_df=load_reference_data(reference_path)
reference_df.head()

,field,code,description,applies_to
0,record_type,observation,Actual measured value from a source,All
1,record_type,event,Policy launch market event or milestone,All
2,record_type,impact_link,Relationship between event and indicator (link...,All
3,record_type,target,Policy target or official goal,All
4,record_type,baseline,Starting point for comparison,All

####  # Examine the structure

In [72]:
# Check rows and columns
check_dimensions(df)

# Display column names
display_columns(df)

# Verify all records have same columns
check_column_consistency(df)

# Show data types
show_column_types(df)

# Generate schema
schema = generate_schema(df)

print(schema)

========== DATASET DIMENSION ==========
Total Records : 43
Total Columns : 34

========== DATASET COLUMNS ==========
1. record_id
2. record_type
3. category
4. pillar
5. indicator
6. indicator_code
7. indicator_direction
8. value_numeric
9. value_text
10. value_type
11. unit
12. observation_date
13. period_start
14. period_end
15. fiscal_year
16. gender
17. location
18. region
19. source_name
20. source_type
21. source_url
22. confidence
23. related_indicator
24. relationship_type
25. impact_direction
26. impact_magnitude
27. impact_estimate
28. lag_months
29. evidence_basis
30. comparable_country
31. collected_by
32. collection_date
33. original_text
34. notes

========== COLUMN CONSISTENCY CHECK ==========
✓ All records have the same columns.

========== COLUMN DATA TYPES ==========
                 Column       Data Type
0             record_id             str
1           record_type             str
2              category             str
3                pillar             str
4             indicator             str
5        indicator_code             str
6   indicator_direction             str
7         value_numeric         float64
8            value_text             str
9            value_type             str
10                 unit             str
11     observation_date  datetime64[us]
12         period_start  datetime64[us]
13           period_end  datetime64[us]
14          fiscal_year          object
15               gender             str
16             location             str
17               region         float64
18          source_name             str
19          source_type             str
20           source_url             str
21           confidence             str
22    related_indicator         float64
23    relationship_type         float64
24     impact_direction         float64
25     impact_magnitude         float64
26      impact_estimate         float64
27           lag_months         float64
28       evidence_basis         float64
29   comparable_country             str
30         collected_by  datetime64[us]
31      collection_date             str
32        original_text             str
33                notes         float64

========== DATASET SCHEMA ==========
            Column Name       Data Type  Missing Values
0             record_id             str               0
1           record_type             str               0
2              category             str              33
3                pillar             str              10
4             indicator             str               0
5        indicator_code             str               0
6   indicator_direction             str              10
7         value_numeric         float64              10
8            value_text             str              33
9            value_type             str               0
10                 unit             str              10
11     observation_date  datetime64[us]               0
12         period_start  datetime64[us]              33
13           period_end  datetime64[us]              33
14          fiscal_year          object               0
15               gender             str               0
16             location             str               0
17               region         float64              43
18          source_name             str               0
19          source_type             str               0
20           source_url             str              12
21           confidence             str               0
22    related_indicator         float64              43
23    relationship_type         float64              43
24     impact_direction         float64              43
25     impact_magnitude         float64              43
26      impact_estimate         float64              43
27           lag_months         float64              43
28       evidence_basis         float64              43
29   comparable_country             str               0
30         collected_by  datetime64[us]               0
31      collection_date             str              33
32        original_text             str              10
33                notes         float64              43

####  # Understand Sheet 1 data

In [79]:
# See available categories
check_record_types(df)

========== AVAILABLE RECORD TYPES ==========
- observation
- target
- event

In [80]:
# Count records
count_records_by_type(df)

========== RECORD COUNTS ==========
record_type
observation    30
event          10
target          3
Name: count, dtype: int64

record_type
observation    30
event          10
target          3
Name: count, dtype: int64

In [81]:
# Analyze observations
observations = analyze_observations(df)

========== OBSERVATION RECORDS ==========
Number of observations: 30

Sample observations:
  record_id  record_type category  pillar               indicator  \
0  REC_0001  observation      NaN  ACCESS  Account Ownership Rate
1  REC_0002  observation      NaN  ACCESS  Account Ownership Rate
2  REC_0003  observation      NaN  ACCESS  Account Ownership Rate
3  REC_0004  observation      NaN  ACCESS  Account Ownership Rate
4  REC_0005  observation      NaN  ACCESS  Account Ownership Rate

  indicator_code indicator_direction  value_numeric value_text  value_type  \
0  ACC_OWNERSHIP       higher_better           22.0        NaN  percentage
1  ACC_OWNERSHIP       higher_better           35.0        NaN  percentage
2  ACC_OWNERSHIP       higher_better           46.0        NaN  percentage
3  ACC_OWNERSHIP       higher_better           56.0        NaN  percentage
4  ACC_OWNERSHIP       higher_better           36.0        NaN  percentage

   ... impact_direction impact_magnitude impact_estimate lag_months  \
0  ...              NaN              NaN             NaN        NaN
1  ...              NaN              NaN             NaN        NaN
2  ...              NaN              NaN             NaN        NaN
3  ...              NaN              NaN             NaN        NaN
4  ...              NaN              NaN             NaN        NaN

  evidence_basis comparable_country collected_by  collection_date  \
0            NaN    Example_Trainee   2025-01-20              NaN
1            NaN    Example_Trainee   2025-01-20              NaN
2            NaN    Example_Trainee   2025-01-20              NaN
3            NaN    Example_Trainee   2025-01-20              NaN
4            NaN    Example_Trainee   2025-01-20              NaN

          original_text notes
0         Baseline year   NaN
1                   NaN   NaN
2                   NaN   NaN
3  Gender disaggregated   NaN
4  Gender disaggregated   NaN

[5 rows x 34 columns]

In [82]:
#  Analyze events
events = analyze_events(df)

========== EVENT RECORDS ==========
Number of events: 10

Sample events:
   record_id record_type        category pillar  \
33  EVT_0001       event  product_launch    NaN
34  EVT_0002       event    market_entry    NaN
35  EVT_0003       event  product_launch    NaN
36  EVT_0004       event  infrastructure    NaN
37  EVT_0005       event          policy    NaN

                               indicator indicator_code indicator_direction  \
33                       Telebirr Launch   EVT_TELEBIRR                 NaN
34  Safaricom Ethiopia Commercial Launch  EVT_SAFARICOM                 NaN
35                M-Pesa Ethiopia Launch      EVT_MPESA                 NaN
36      Fayda Digital ID Program Rollout      EVT_FAYDA                 NaN
37       Foreign Exchange Liberalization  EVT_FX_REFORM                 NaN

    value_numeric   value_text   value_type  ... impact_direction  \
33            NaN     Launched  categorical  ...              NaN
34            NaN     Launched  categorical  ...              NaN
35            NaN     Launched  categorical  ...              NaN
36            NaN     Launched  categorical  ...              NaN
37            NaN  Implemented  categorical  ...              NaN

   impact_magnitude impact_estimate lag_months evidence_basis  \
33              NaN             NaN        NaN            NaN
34              NaN             NaN        NaN            NaN
35              NaN             NaN        NaN            NaN
36              NaN             NaN        NaN            NaN
37              NaN             NaN        NaN            NaN

   comparable_country collected_by  collection_date  \
33    Example_Trainee   2025-01-20              NaN
34    Example_Trainee   2025-01-20              NaN
35    Example_Trainee   2025-01-20              NaN
36    Example_Trainee   2025-01-20              NaN
37    Example_Trainee   2025-01-20              NaN

                                   original_text notes
33  First major mobile money service in Ethiopia   NaN
34                 End of state telecom monopoly   NaN
35                   Second mobile money entrant   NaN
36          National biometric digital ID system   NaN
37                         Birr float introduced   NaN

[5 rows x 34 columns]

In [83]:
# Analyze targets
targets = analyze_targets(df)

========== TARGET RECORDS ==========
Number of targets: 3

Sample targets:
   record_id record_type category  pillar                          indicator  \
30  REC_0031      target      NaN  ACCESS             Account Ownership Rate
31  REC_0032      target      NaN  ACCESS        Fayda Digital ID Enrollment
32  REC_0033      target      NaN  GENDER  Female Mobile Money Account Share

   indicator_code indicator_direction  value_numeric value_text  value_type  \
30  ACC_OWNERSHIP       higher_better           70.0        NaN  percentage
31      ACC_FAYDA       higher_better     90000000.0        NaN       count
32   GEN_MM_SHARE       higher_better           50.0        NaN  percentage

    ... impact_direction impact_magnitude impact_estimate lag_months  \
30  ...              NaN              NaN             NaN        NaN
31  ...              NaN              NaN             NaN        NaN
32  ...              NaN              NaN             NaN        NaN

   evidence_basis comparable_country collected_by  collection_date  \
30            NaN    Example_Trainee   2025-01-20              NaN
31            NaN    Example_Trainee   2025-01-20              NaN
32            NaN    Example_Trainee   2025-01-20              NaN

         original_text notes
30      NFIS-II target   NaN
31  90M by 2028 target   NaN
32       Parity target   NaN

[3 rows x 34 columns]

In [84]:
# Compare all categories
compare_record_categories(df)

========== CATEGORY COMPARISON ==========
   record_type  Number of Records
0        event                 10
1  observation                 30
2       target                  3

   record_type  Number of Records
0        event                 10
1  observation                 30
2       target                  3

####  # Understand Sheet 2 data

In [93]:
# Understand structure
examine_impact_structure(impact_df)

========== IMPACT LINKS STRUCTURE ==========
Number of Records: 14
Number of Columns: 35

Columns:
- record_id
- parent_id
- record_type
- category
- pillar
- indicator
- indicator_code
- indicator_direction
- value_numeric
- value_text
- value_type
- unit
- observation_date
- period_start
- period_end
- fiscal_year
- gender
- location
- region
- source_name
- source_type
- source_url
- confidence
- related_indicator
- relationship_type
- impact_direction
- impact_magnitude
- impact_estimate
- lag_months
- evidence_basis
- comparable_country
- collected_by
- collection_date
- original_text
- notes

Data Types:
record_id                         str
parent_id                         str
record_type                       str
category                      float64
pillar                            str
indicator                         str
indicator_code                float64
indicator_direction           float64
value_numeric                 float64
value_text                    float64
value_type                        str
unit                              str
observation_date       datetime64[us]
period_start                  float64
period_end                    float64
fiscal_year                   float64
gender                            str
location                          str
region                        float64
source_name                   float64
source_type                   float64
source_url                    float64
confidence                        str
related_indicator                 str
relationship_type                 str
impact_direction                  str
impact_magnitude                  str
impact_estimate               float64
lag_months                      int64
evidence_basis                    str
comparable_country                str
collected_by                      str
collection_date        datetime64[us]
original_text                 float64
notes                             str
dtype: object

In [94]:
# View relationships
summarize_relationships(impact_df)

========== RELATIONSHIP SUMMARY ==========
  record_id parent_id  record_type  category         pillar  \
0  IMP_0001  EVT_0001  impact_link       NaN         ACCESS
1  IMP_0002  EVT_0001  impact_link       NaN          USAGE
2  IMP_0003  EVT_0001  impact_link       NaN          USAGE
3  IMP_0004  EVT_0002  impact_link       NaN         ACCESS
4  IMP_0005  EVT_0002  impact_link       NaN  AFFORDABILITY

                                indicator  indicator_code  \
0    Telebirr effect on Account Ownership             NaN
1       Telebirr effect on Telebirr Users             NaN
2     Telebirr effect on P2P Transactions             NaN
3         Safaricom effect on 4G Coverage             NaN
4  Safaricom effect on Data Affordability             NaN

   indicator_direction  value_numeric  value_text  ... impact_direction  \
0                  NaN           15.0         NaN  ...         increase
1                  NaN            NaN         NaN  ...         increase
2                  NaN           25.0         NaN  ...         increase
3                  NaN           15.0         NaN  ...         increase
4                  NaN          -20.0         NaN  ...         decrease

  impact_magnitude impact_estimate  lag_months  evidence_basis  \
0             high            15.0          12      literature
1             high             NaN           3       empirical
2             high            25.0           6       empirical
3           medium            15.0          12       empirical
4           medium           -20.0          12      literature

   comparable_country     collected_by collection_date  original_text  \
0               Kenya  Example_Trainee      2025-01-20            NaN
1                 NaN  Example_Trainee      2025-01-20            NaN
2                 NaN  Example_Trainee      2025-01-20            NaN
3                 NaN  Example_Trainee      2025-01-20            NaN
4              Rwanda  Example_Trainee      2025-01-20            NaN

                                    notes
0  Kenya M-Pesa showed +20pp over 5 years
1           Direct subscriber acquisition
2             New digital payment channel
3     Network investment from competition
4    Competition typically reduces prices

[5 rows x 35 columns]

Missing Values:
record_id               0
parent_id               0
record_type             0
category               14
pillar                  0
indicator               0
indicator_code         14
indicator_direction    14
value_numeric           2
value_text             14
value_type              0
unit                    0
observation_date        0
period_start           14
period_end             14
fiscal_year            14
gender                  0
location                0
region                 14
source_name            14
source_type            14
source_url             14
confidence              0
related_indicator       0
relationship_type       0
impact_direction        0
impact_magnitude        0
impact_estimate         2
lag_months              0
evidence_basis          0
comparable_country      7
collected_by            0
collection_date         0
original_text          14
notes                   0
dtype: int64

In [95]:
# Analyze impact
analyze_impact(impact_df)

========== IMPACT ANALYSIS ==========
Available columns:
['record_id', 'parent_id', 'record_type', 'category', 'pillar', 'indicator', 'indicator_code', 'indicator_direction', 'value_numeric', 'value_text', 'value_type', 'unit', 'observation_date', 'period_start', 'period_end', 'fiscal_year', 'gender', 'location', 'region', 'source_name', 'source_type', 'source_url', 'confidence', 'related_indicator', 'relationship_type', 'impact_direction', 'impact_magnitude', 'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country', 'collected_by', 'collection_date', 'original_text', 'notes']

#### # Review reference code data Valid Field Values

In [97]:
# Review Valid Field Values
review_valid_values(reference_df)

========== VALID FIELD VALUES ==========

Field: field
Valid Values:
- record_type
- category
- pillar
- indicator_direction
- value_type
- source_type
- confidence
- gender
- location
- relationship_type
- impact_direction
- impact_magnitude
- evidence_basis
Total Valid Values: 13

Field: code
Valid Values:
- observation
- event
- impact_link
- target
- baseline
- forecast
- product_launch
- market_entry
- market_exit
- policy
- regulation
- infrastructure
- partnership
- milestone
- economic
- pricing
- ACCESS
- USAGE
- QUALITY
- AFFORDABILITY
- TRUST
- DEPTH
- GENDER
- higher_better
- lower_better
- neutral
- percentage
- count
- currency_etb
- currency_usd
- ratio
- rate
- index
- gap_pp
- boolean
- categorical
- text
- survey
- operator
- regulator
- news
- research
- calculated
- field
- high
- medium
- low
- estimated
- all
- male
- female
- national
- urban
- rural
- direct
- indirect
- enabling
- constraining
- increase
- decrease
- stabilize
- mixed
- negligible
- empirical
- literature
- theoretical
- expert
Total Valid Values: 67

Field: description
Valid Values:
- Actual measured value from a source
- Policy launch market event or milestone
- Relationship between event and indicator (links via parent_id)
- Policy target or official goal
- Starting point for comparison
- Predicted future value
- New product or service introduced
- New competitor enters market
- Competitor leaves market
- Government strategy or regulatory framework
- Specific regulatory directive or rule change
- System or network deployment
- Integration or cooperation between entities
- Achievement or threshold crossed
- Macro-economic shock or reform
- Price or tariff change
- Can people reach services? Coverage devices accounts
- Are people actively using? Transactions active users
- Do services work? Success rates uptime
- Can people afford it? Costs relative to income
- Do people trust it? Complaints fraud
- Beyond payments? Savings credit insurance
- Gender gaps across dimensions
- Higher values indicate better outcomes
- Lower values indicate better outcomes
- Direction depends on context
- Value 0-100 representing a rate or proportion
- Integer count of items transactions users
- Monetary value in Ethiopian Birr
- Monetary value in US Dollars
- Ratio of two values unitless
- Normalized rate per population unit
- Composite score typically 0-100 or 0-1
- Difference between two percentages in percentage points
- Yes/No True/False 1/0
- Discrete category or status
- Descriptive text
- Demand-side household survey (Findex FinScope)
- Company reports and data (Ethio Telecom Safaricom EthSwitch)
- Central bank or government data (NBE NIDP)
- Strategy documents directives proclamations
- News articles press releases announcements
- Academic papers think tank reports (GSMA IMF World Bank)
- Derived from other indicators in this dataset
- Primary data collected by trainees
- Primary source verified official data
- Secondary source cross-referenced
- Single source unverified
- Calculated or interpolated
- Aggregate figure for all genders
- Male-specific figure
- Female-specific figure
- Country-wide aggregate
- Urban areas only
- Rural areas only
- Event directly causes change in indicator
- Event causes change through intermediate mechanism
- Event creates conditions for future change
- Event limits potential improvement
- Expected to raise indicator value
- Expected to lower indicator value
- Expected to maintain current level
- Direction unclear or varies
- Major impact greater than 15% change expected
- Moderate impact 5-15% change expected
- Minor impact less than 5% change expected
- Very small impact less than 1% change expected
- Based on observed Ethiopian data
- Based on research from other countries
- Based on economic theory
- Domain expert judgment
Total Valid Values: 71

Field: applies_to
Valid Values:
- All
- event
- observation/target/impact_link
- observation
- impact_link
Total Valid Values: 5

#### # Understand challenges how the impact connect

In [100]:
 #Understand event pillars
events = analyze_event_pillars(df)

========== EVENT PILLAR ANALYSIS ==========
Total Events: 10

Available Columns:
['record_id', 'record_type', 'category', 'pillar', 'indicator', 'indicator_code', 'indicator_direction', 'value_numeric', 'value_text', 'value_type', 'unit', 'observation_date', 'period_start', 'period_end', 'fiscal_year', 'gender', 'location', 'region', 'source_name', 'source_type', 'source_url', 'confidence', 'related_indicator', 'relationship_type', 'impact_direction', 'impact_magnitude', 'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country', 'collected_by', 'collection_date', 'original_text', 'notes']

Pillar Distribution:
pillar
NaN    10
Name: count, dtype: int64

In [101]:
# Check pillar assignment problems
check_pillar_challenges(events)

========== PILLAR ASSIGNMENT CHALLENGES ==========
Missing pillar values: 10

Existing pillar values:
<StringArray>
[nan]
Length: 1, dtype: str

Common Challenges:

1. One event can belong to multiple pillars.
   Example:
   Mobile banking launch:
   - Digital access
   - Product innovation

2. Different sources may use different names.
   Example:
   product launch vs product_launch

3. Some events may have unclear impact category.

4. Historical events may lack pillar information.

In [106]:
#  Connect events to indicators
connections = analyze_parent_id_links(events,impact_df)

========== IMPACT LINK CONNECTION ==========
Events: 10
Impact Links: 14

Sample impact connections:
  record_id parent_id record_type_x  category_x       pillar_x  \
0  IMP_0001  EVT_0001   impact_link         NaN         ACCESS
1  IMP_0002  EVT_0001   impact_link         NaN          USAGE
2  IMP_0003  EVT_0001   impact_link         NaN          USAGE
3  IMP_0004  EVT_0002   impact_link         NaN         ACCESS
4  IMP_0005  EVT_0002   impact_link         NaN  AFFORDABILITY

                              indicator_x  indicator_code_x  \
0    Telebirr effect on Account Ownership               NaN
1       Telebirr effect on Telebirr Users               NaN
2     Telebirr effect on P2P Transactions               NaN
3         Safaricom effect on 4G Coverage               NaN
4  Safaricom effect on Data Affordability               NaN

   indicator_direction_x  value_numeric_x  value_text_x  ...  \
0                    NaN             15.0           NaN  ...
1                    NaN              NaN           NaN  ...
2                    NaN             25.0           NaN  ...
3                    NaN             15.0           NaN  ...
4                    NaN            -20.0           NaN  ...

  impact_direction_y impact_magnitude_y impact_estimate_y  lag_months_y  \
0                NaN                NaN               NaN           NaN
1                NaN                NaN               NaN           NaN
2                NaN                NaN               NaN           NaN
3                NaN                NaN               NaN           NaN
4                NaN                NaN               NaN           NaN

   evidence_basis_y  comparable_country_y collected_by_y collection_date_y  \
0               NaN                   NaN            NaT               NaN
1               NaN                   NaN            NaT               NaN
2               NaN                   NaN            NaT               NaN
3               NaN                   NaN            NaT               NaN
4               NaN                   NaN            NaT               NaN

   original_text_y  notes_y
0              NaN      NaN
1              NaN      NaN
2              NaN      NaN
3              NaN      NaN
4              NaN      NaN

[5 rows x 68 columns]

Connected Records:
14

### 2.	Explore the Data

In [ ]:
# Count record types
record_summary = count_by_record_type(df)

# Count pillars
pillar_summary = count_by_pillar(df)

# Count source types
source_summary = count_by_source_type(df)

# Count confidence levels
confidence_summary = count_by_confidence(df)

========== RECORD TYPE COUNT ==========
   Record Type  Count
0  observation     30
1        event     10
2       target      3

========== PILLAR COUNT ==========
          Pillar  Count
0         ACCESS     16
1          USAGE     11
2            NaN     10
3         GENDER      5
4  AFFORDABILITY      1

========== SOURCE TYPE COUNT ==========
  Source Type  Count
0    operator     15
1      survey     10
2   regulator      7
3    research      4
4      policy      3
5  calculated      2
6        news      2

========== CONFIDENCE COUNT ==========
  Confidence  Count
0       high     40
1     medium      3

#### # Identify the temporal range of observations

In [ ]:
# Run temporal analysis
temporal_summary = identify_observation_temporal_range(df)